### ISSUE TITLE
IOC and FIFA code

### ISSUE THREAD

**Issue by Filoz** [7kfpun/flag-css#2]
Hi, 
What do you think about adding the IOC and FIFA code?
https://en.wikipedia.org/wiki/Comparison_of_IOC,_FIFA,_and_ISO_3166_country_codes

They are used for sports competitions.

Thankyou!

**Comment by 7kfpun** [comment]
Supported in version 0.0.3
Thanks!

**Comment by Filoz** [comment]
Thankyou! :)
