### ISSUE TITLE
flag-list.scss compiler errors

### ISSUE THREAD

**Issue by murraybiscuit** [7kfpun/flag-css#5]
I'm getting multiple compiler errors in this file:
OS: Windows 10
Compiler: node-sass@3.8.0
1. Line 23:  `@if $ioc = null`...
   assignment operator ( = ) is used in stead of evaluation operator ( == ). This holds for other @if/else conditionals
2. Line 53: `@include flag(and, ad, 20, and, and);`
   Line 276: `@include flag(tza, tz, 834, tan, tan);`
   arguments aren't quoted, resulting in errors on the mixin - reserved words `and` and `tan` seem to be throwing the error.

**Comment by ProNotion** [comment]
Have you managed to resolve this? We have the same compile errors.

**Comment by 7kfpun** [comment]
I don't have Windows. Could you PR?

**Comment by ProNotion** [comment]
To submit a PR I would need to first find the cause and implement a solution?

**Comment by murraybiscuit** [comment]
Yeah, I resolved. The issue was with the naming convention used - as per my OP, the string concatenation threw errors when the compiler did an eval and ran into the reserved words. I think I ended up quoting or back ticking or something I'll take a look at it today...

**Comment by ProNotion** [comment]
Thanks that would be really helpful.

**Comment by murraybiscuit** [comment]
@ProNotion sorry about the long wait, please see pull request added above.

**Comment by 7kfpun** [comment]
Thanks @murraybiscuit !

**Comment by ProNotion** [comment]
@murraybiscuit Thanks that's great. @7kfpun will there be a Bower package update with this fix?

Thanks guys!

**Comment by 7kfpun** [comment]
Yes, soon!
